# Generated by Django 3.1.3 on 2022-03-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name', 'id'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
