# Generated by Django 3.1.3 on 2022-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20220324_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(default=models.CharField(max_length=64, unique=True), max_length=64),
        ),
    ]
