# Generated by Django 3.1.3 on 2022-04-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0006_auto_20220327_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name="Route's name")),
                ('travel_duration', models.PositiveSmallIntegerField(verbose_name='Trip duration')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_endpoint_set', to='cities.city', verbose_name='Trip ends at:')),
                ('startpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_startpoint_set', to='cities.city', verbose_name='Trip starts from:')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['startpoint', 'endpoint', 'name'],
            },
        ),
    ]
