# Generated by Django 3.1.3 on 2022-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='trains',
            field=models.ManyToManyField(to='trains.Train', verbose_name='List of trains'),
        ),
    ]
